### ISSUE TITLE
sessionizeで作成したタイムテーブルに遷移できる

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#102]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/21273221/133878932-d6670a51-2460-46ae-bc35-8c36d6d954f9.png">

「Search talks」ボタンの変更をお願いします

## 変更後

- ボタンの表示「Timetable (beta)」
- リンク先：https://sessionize.com/view/eu4z8c9d/GridSmart?format=Embed_Styled_Html&isDark=False

**Comment by papi-tokei** [comment]
@ftnext 
修正し本番環境へ反映しましたー

**Comment by ftnext** [comment]
反映ありがとうございます。
確認しました！
