### ISSUE TITLE
サイト上でスポンサー募集要項・スポンサー申し込みのリンクが見られなくなっている

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#114]
スポンサー募集が終了したので、提案いただいた措置をお願いします
ref: https://pyconjp.slack.com/archives/C01M5K8JKKN/p1632156568111000

**Comment by k-nakamura** [comment]
#126 と合わせて修正

**Comment by k-nakamura** [comment]
メニューの
- スポンサー募集要項
- スポンサー申し込み

の2つのリンクを以下のように変更しました。

- 灰色かつ打ち消し線をつけて表示
- リンク先をhttps://pyconjp.blogspot.com/2021/09/closed-sponsor-application.html に変更

**Comment by ftnext** [comment]
本番環境で動作確認し、よさそうです。
対応ありがとうございました
