### ISSUE TITLE
フッターの「過去のPyCon JPのサイト一覧」のリンクを有効にしたい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#12]
この箇所
<img width="425" alt="image" src="https://user-images.githubusercontent.com/21273221/127172628-b03e40c4-167c-41a1-a984-622885234536.png">

Miroのサイトマップのコメントを参照すると
 https://www.pycon.jp/organizer/index.html へのリンクです。
これが別のタブで開くといいのではないかと思います

新しいページを作るわけではなくリンクの有効化なので、すぐできそうだと思っています。
フッターを見たときにクリックできそうに見えるので、有効化したほうがいいと思います。
すぐできて、効果がありそうだからやってしまいましょう

**Comment by k-nakamura** [comment]
@ftnext 
こちらのプルリクエストで合わせて対応しました。
https://github.com/pyconjp/pycon.jp.2021/pull/13

**Comment by k-nakamura** [comment]
フッターのロゴに以下のリンク先を設定
https://www.pycon.jp/

**Comment by ftnext** [comment]
> @ftnext
> こちらのプルリクエストで合わせて対応しました。
> #13

develop環境でリンクが追加されているのを確認しました。
対応ありがとうございます。 @k-nakamura 

master環境（本番環境）の方へも反映お願いします

**Comment by ftnext** [comment]
9日のデプロイの後、本番環境で確認できました。
Closeします。
対応ありがとうございました
