### ISSUE TITLE
PyCon JP 2021サイトから感染症対策ガイドラインに遷移できる

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#126]
感染症対策ガイドラインへの動線の件です。

https://drive.google.com/file/d/1abgh7glVaUsYnlRf_v2RLYw2V3ZAGnjt/view?usp=sharing に遷移できるようにしてください

ワイヤーフレーム段階では、オンサイト会場の情報を出す項目があったと思うので、そこに入れればいいのではないかと考えています

**Comment by papi-tokei** [comment]
ヘッダータイトルは「感染症対策ガイドライン」

**Comment by k-nakamura** [comment]
メニューへの追加は #114 で対応。

**Comment by ftnext** [comment]
スマホで動作確認。メニューの「感染症対策ガイドライン」から遷移できました
![image](https://user-images.githubusercontent.com/21273221/135743434-3942f256-8a82-49a5-8847-9eca18d322c4.jpeg)

ありがとうございました
