### ISSUE TITLE
タイムテーブルのページのヘッダーをスティッキーに修正する

### ISSUE THREAD

**Issue by papi-tokei** [pyconjp/pycon.jp.2021#134]
タイムテーブルのページのヘッダーをスクロールでついてくるように修正する

**Comment by kingkoma** [comment]
# 修正後

<img width="1258" alt="Snipaste_2021-10-01_20-04-21" src="https://user-images.githubusercontent.com/33335362/135610740-b2061015-a9a1-4c63-8a35-aec8de987210.png">

**Comment by kingkoma** [comment]
@papi-tokei 修正して開発環境に反映されましたので、ご確認頂ければと思います。

**Comment by papi-tokei** [comment]
ありがとうございます。
確認しました。
