### ISSUE TITLE
タイムテーブルにスペシャルブース紹介とAsk the speaker/ スペシャルブース訪問 を追加する

### ISSUE THREAD

**Issue by papi-tokei** [pyconjp/pycon.jp.2021#147]
スペシャルブース紹介は優先度高

Ask the speakerは優先度は低め、ただし、トークの時間を追加するのは優先度高め。

**Comment by ftnext** [comment]
10/2の作業会で話し、2020のタイムテーブルのようにする

- トークの時間を出す（デザイン確認中）
- スペシャルブース紹介も出す
- 「Ask the speaker / スペシャルブース訪問」は休憩時間なのでタイムテーブルには出さない

**Comment by papi-tokei** [comment]
別課題と重複するためクローズする
