### ISSUE TITLE
トークの詳細（モーダル）からLevelの定義に遷移できる

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#180]
2020を見ていて気づいたのですが、
https://pycon.jp/2020/timetable/?id=203955
Levelの値がLevelの定義のブログへとリンクになっています。

プロポーザルを出さない人にどれくらいLevelが伝わっているか自信がなく、関心のある人が定義を見えるようにリンクを追加したいです。
（優先度はTrackが先、LevelはTrackと比べると落とせます）

2021のサイトでは https://pyconjp.blogspot.com/2021/05/2021-proposal-audience.html へのリンクになります

実現方法案

- Levelからリンクにしてしまう
- Levelの値があればそれをリンクにする（Allもリンクにする。4レベルとも対象ということなので）

**Comment by kingkoma** [comment]
@ftnext 開発環境へ反映されましたので、ご確認頂ければ幸いです。

**Comment by ftnext** [comment]
@kingkoma 対応ありがとうございます。
こちらもイメージ通りです。
本番環境にリリースお願いします

**Comment by ftnext** [comment]
本番に反映されていて、よさそうでした。ありがとうございました
