### ISSUE TITLE
match文を使った会場の表記を修正したい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#21]
以下の部分です
<img width="478" alt="image" src="https://user-images.githubusercontent.com/21273221/127774059-eed86d9a-cac3-4941-9b0a-8b0bd0ee144f.png">

こうしたい（プロンプトは外して大丈夫です）

```python
>>> match PyConJP(2021):
...   case "ONLINE": Zoom
...   case "ONSITE": ベルサール神田
```

- (MUST) PyConJP: Cは大文字
- (IMO) ベルサール神田の前に半角スペース1つを入れたい（Zoomの方と揃えたい）
- (MUST) `["ONLINE"]` とリストにしていたのは過剰だったとわかった（以前の私の提案が間違っていた）ので、単に文字列にしたいです

ref: https://docs.python.org/3.10/whatsnew/3.10.html#pep-634-structural-pattern-matching

---

`docker run --rm -it python:3.10.0b4-buster python` して、Python 3.10b4 で動くことを確認済み
（以下の実装だとどちらのパターンにもマッチしません）

```python
>>> from dataclasses import dataclass
>>> @dataclass
... class PyConJP:
...   year: int
...
>>> class Zoom: ...
...
>>> class ベルサール神田: ...
...
>>> match PyConJP(2021):
...   case "ONLINE": Zoom
...   case "ONSITE": ベルサール神田
...
>>>
```

**Comment by peacock0803sz** [comment]
Offline/Onsiteで表記揺れしているので一緒に直してしまいましょうか?
場所は見つけたので直せます
https://github.com/pyconjp/pycon.jp.2021/blob/master/components/Doamins/TopPage/MainVisual.vue#L30

**Comment by peacock0803sz** [comment]
```python
>>> match PyConJP(2021):
...   case "ONLINE": Zoom
...   case "ONSITE": ベルサール神田
```
の表記がPython的に正しいかはちょっと疑問です。
そのコード内ではエラー起きてない(手元でも確認できた)ですが...
少なくともこんな感じにする必要があるかと。サイトに載せるのはmatch文のところでいいと思いますが

```python
>>> from dataclasses import dataclass
>>> from typing import Literal
>>>
>>> @dataclass
... class PyConJP:
...   year: int
...   venue: Literal["Hybrid", "Online"]
...
>>>
>>> place: str
>>> pyconjp_2021 = PyConJP(2021, "Hybrid")
>>>
>>> match pyconjp_2021.venue:
...   case "Online": place = "Zoom"
...   case "Hybrid": place = "ベルサール神田"
...
>>> place
'ベルサール神田'
```

**Comment by ftnext** [comment]
match文以外の表記揺れ直すのはIssueを分けたいです。
このIssueではmatch文だけを扱いましょう

**Comment by ftnext** [comment]
今のコード、エラーがないのでOKだと思っています。
ちなみにインスパイアされたのが
https://tw.pycon.org/2021/en-us
のwith文です。
これはコードではなく洒落た表現なので、Pythonコードとしての意味にこだわる必要はないと考えています

**Comment by papi-tokei** [comment]
@ftnext @peacock0803sz 
修正して開発環境に反映しましたのでご確認頂ければと思います。

**Comment by ftnext** [comment]
本番環境で「こうしたい」の表記になっていることを確認しました。
Closeします。
対応ありがとうございました。
