### ISSUE TITLE
タイムテーブルでトーク詳細からアーカイブ動画に遷移できる

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#222]
10/18 全体mtg でMiroに出たタスクを追加します

>Webサイトのタイムテーブルにアーカイブ動画へのリンクを設置

YouTubeでのアーカイブ公開後に対応お願いします

**Comment by ftnext** [comment]
https://pyconjp.slack.com/archives/C01M5K8JKKN/p1638980149012500 にて依頼

**Comment by k-nakamura** [comment]
@ftnext 
公開可能な全ての動画をSessionizeに登録しました。
12/10(金)の日次デプロイで本番環境に反映されます。

**Comment by ftnext** [comment]
本番環境のタイムテーブルをいくつか見て、Videoのリンクが有効になり遷移することを確認しました。
対応ありがとうございます
