### ISSUE TITLE
SP画面でスポンサーのリンクが無い場合、別ページで自分自身のサイトが開く

### ISSUE THREAD

**Issue by papi-tokei** [pyconjp/pycon.jp.2021#24]

**Comment by kingkoma** [comment]
@papi-tokei 
修正して開発環境に反映しましたのでご確認頂ければと思います。

## 参考情報
- [https://github.com/taye/interact.js/issues/595](url)
- [https://stackoverflow.com/questions/3918842/how-to-find-out-the-actual-event-target-of-touchmove-javascript-event](url)
- [https://stackoverflow.com/questions/59084929/pointer-events-none-doesnt-work-on-mobile](url)

**Comment by papi-tokei** [comment]
@kingkoma 
修正ありがとうございます。
確認できましたのでクローズさせて頂きます。
