### ISSUE TITLE
ファーストビューのTime Table Coming Soonボタンを採択速報へのリンクにして有効にしたい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#34]
8/9の全体mtgで話した件ですが、以下へのリンクをお願いします
https://pyconjp.blogspot.com/2021/08/pyconjp-2021-proposal-selection.html

ボタンのテキスト案「Adopted Proposals」

ボタンの下側に地の文でTime Table Coming Soonとあるとさらによさそうです。
nice to haveとして、「Time Table Coming Soon」はボタンにマウスカーソルをホバーしたときにツールチップとしてでたらいいなと思っています

現状
<img width="492" alt="image" src="https://user-images.githubusercontent.com/21273221/128714483-d3d7ebd8-a8f6-4c76-9ce4-996be7f9958f.png">

**Comment by kingkoma** [comment]
対応しましたので、クローズいたします。

**Comment by kingkoma** [comment]
@papi-tokei  
申し訳ありませんでした、作業の流れを間違えました。
修正して開発環境に反映しましたのでご確認頂ければと思います。
よろしくお願いいたします。

**Comment by ftnext** [comment]
対応ありがとうございました。
PCの方で表示とリンク先の確認ができているので、クローズします
