### ISSUE TITLE
iPhone 11 Pro、ChromeでAdopted Proposalのボタンの表示修正

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#38]
https://pyconjp.slack.com/archives/C01M5K8JKKN/p1628608851089300 の件

![image](https://user-images.githubusercontent.com/21273221/129059821-6c916f4c-2216-4cdc-8c58-a64f451b03f8.jpeg)

https://twitter.com/satohmsys/status/1424935707475202053?s=21 を試してみました。
デバイス情報
デバイスピクセル比
3
画面の幅
375 px
画面の高さ
812 px
画面の幅（有効領域）
375 px
画面の高さ（有効領域）
812 px
ウインドウの幅
375 px
ウインドウの高さ
730 px

**Comment by ftnext** [comment]
開発環境で修正確認できました。
ありがとうございます。
![image](https://user-images.githubusercontent.com/21273221/129135234-67547ecb-fe82-4ce0-9bde-83fc672c0217.jpeg)

@kingkoma 本番環境への反映をお願いします

**Comment by kingkoma** [comment]
@papi-tokei [https://github.com/pyconjp/pycon.jp.2021/pull/41](url) レビューをお願いいたします。

**Comment by kingkoma** [comment]
@ftnext
開発環境に反映しましたのでご確認頂ければと思います。
よろしくお願いいたします。

**Comment by ftnext** [comment]
本番環境でも修正されていました。
ありがとうございます！

![image](https://user-images.githubusercontent.com/21273221/129449674-e2268fc1-79df-4f2a-8c06-15e0b047ca59.jpeg)
