### ISSUE TITLE
トップページのconnpassへのリンクを有効化する

### ISSUE THREAD

**Issue by k-nakamura** [pyconjp/pycon.jp.2021#68]
トップページのTicketボタンにconnpassへのリンク(https://pyconjp.connpass.com/event/221241/ )を設置する

**Comment by papi-tokei** [comment]
@k-nakamura @ftnext 

本番環境へ反映済みです。
ご確認お願いします。

**Comment by k-nakamura** [comment]
@papi-tokei 

デプロイありがとうございます。
正常に動作することが確認できました。
