### ISSUE TITLE
ファーストビューのAdopted ProposalsボタンをSearch Talksボタンに切り替えたい

### ISSUE THREAD

**Issue by ftnext** [pyconjp/pycon.jp.2021#72]
#34 で設定してもらったボタンですが、FAQブログで案内している「トークを検索できる簡易アプリ」へのリンクに差し替えをお願いします
https://pyconjp.blogspot.com/2021/08/pyconjp2021-faq-conference-ticket.html

- リンク先：https://share.streamlit.io/pyconjp/talks.searcher.2021/main/app.py
- テキスト案：Search Talks
- ブラウザの別のタブで開く挙動でお願いします

**Comment by papi-tokei** [comment]
@ftnext 
修正して本番環境へ反映済みです。
ご確認よろしくお願いします。

**Comment by ftnext** [comment]
確認できました。
対応ありがとうございます
